version: "3.8"
services:

  nginx_server:
    container_name: nginx-server 
    image: nginx
    ports:
      - containerPort: 8000 
    networks:
      - project_network 
    depends_on:
      - application 
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf 

  application:
    container_name: application-server 
    build: . 
    ports:
      - containerPort: 8001 
        protocol: TCP 
    healthcheck:
      test: ["curl", "-f", "http://localhost:8001/ping/"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 10s 

    env_file:
      - ../project.env 

    depends_on:
      - postgres_database
    networks:
      - project_network 

  postgres_database:
    container_name: database 
    image: postgres:latest 
    ports:
      - containerPort: 5432 
        protocol: TCP 
    networks:
      - project_network 
    environment:
      POSTGRES_DB: postgres_db 
      POSTGRES_USER: postgres_user 
      POSTGRES_PASSWORD: postgres_password 

networks:
  project_network:
    - external: true 
      name: project_network
    

