apiVersion: v1
kind: Service 
metadata:
  name: application-service
  namespace: app-namespace 
spec:
  type: ClusterIP 
  selector:
    app: contract-app 
  ports:
    - name: http 
      port: 8000 
      protocol: TCP 
      targetPort: 8000 
--- 

apiVersion: v1 
kind: Deployment 
metadata:
  name: application-deployment 
  namespace: app-namespace 
spec:
  selector:
    matchLabels:
      app: contract-app 
  template:
    metadata: 
      labels: 
        app: contract-app 
    spec:
      terminationGracePeriodSeconds: 30 
      containers:
        - name: application-container 
          image: crazycoderrr/contract-app 
          ports:
            - containerPort: 8000
              protocol: TCP 
          envFrom:
            - configMapRef:
                - name: application-config-map  
          imagePullPolicy: IfNotPresent 

--- 

apiVersion: v1
kind: ConfigMap 
metadata:
  name: application-config-map 
  namespace: app-namespace 
spec:
  APPLICATION_HOST: localhost 
  APPLICATION_PORT: 8000 
