apiVersion: v1
kind: Service 
metadata:
  name: postgres 
  namespace: app-namespace 
spec:
  type: ClusterIP 
  selector:
    app: postgres-app 
  ports:
    - name: http  
      port: 5432 
      protocol: TCP 
      targetPort: 5432 

---
apiVersion: v1
kind: StatefulSet 
metadata:
  name: postgres-database 
  namespace: app-namespace 
spec:
  selector:
    matchLabels:
      app: postgres-app 
  template:
    metadata:
      labels:
        app: postgres-app 
    spec:
      containers:
        - name: postgres-container 
          image: postgres:latest 
          ports:
            - containerPort: 5432 
              protocol: TCP 
          envFrom:
            - secretRef:
                - name: postgres-secret 
          imagePullPolicy: IfNotPresent 

          volumeMounts:
            - name: postgres-volume  
              path: /postgresql/lib/data

      volumes:
        - name: postgres-volume 
          persistentVolumeClaim:
            - name: postrgres-claim 

--- 

apiVersion: v1
kind: Secret 
metadata:
  name: postgres-secret 
  namespace: app-namespace 
  annotations:
    kubernetes.io/secret: "Opaque"
stringData:
  POSTGRES_USER: "postgres-user"
  POSTGRES_PASSWORD: "Kirill"
  POSTGRES_PORT: "5432"
 

--- 

# Data Volumes 

apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: postgres-claim 
  namespace: app-namespace 
spec:
  accessModes: 
    - ReadWriteOnce 
  storageClassName: manual 
  resources:
    limits:
      - storage: 4Gi

--- 

apiVersion: v1 
kind: PersistentVolume 
metadata:
  name: postgres-volume 
  namespace: app-namespace 
spec:
  claimRef:
    - name: postgres-claim  
      namespace: app-namespace 
  accessModes: 
    - ReadWriteOnce 
  storageClassName: manual 
  capacity:
    - storage: 5Gi 
  hostPath: /mnt/data  
